default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  post: <%= ENV['DATABASE_PORT'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test
